excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://commitcast.github.io
title: CommitCast
email: commitcast@godrix.com
author: CommitCast
description: $ commit -m 'first commit'
paginate: 3
google_analytics: 
